### ISSUE TITLE
[QUESTION] - refresh from thread::spawn possible?

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#11]
Firstly, I'm not sure if this is related to tuirealm, seems to me like a more general question. But since I'm using tuirealm, probably you're the best person to answer it.

I'm building a terminal music player using tuirealm and it's working already(https://github.com/tramhao/termusic). I'm implementing a download feature for it. Due to the fact that download will take several seconds, I don't want the app to stuck so I use thread::spawn to run the download in a thread. However, after download, I need 2 things done: if the download is succseeful, I need refresh the treeview(by self.refresh()). If not successful, I need to show an error message(by msgbox). How can I access self.refresh or self.mount_error() in thread? The compiler complain below code that self cannot be moved.
I've searched for 1 day for this single problem...Thanks so much.

```
    pub fn youtube_dl(&mut self, link: String) {
        let args = vec![
            Arg::new("--quiet"),
            Arg::new("--extract-audio"),
            Arg::new_with_arg("--audio-format", "mp3"),
            Arg::new("--add-metadata"),
            Arg::new("--embed-thumbnail"),
            Arg::new_with_arg("--metadata-from-title", "%(artist) - %(title)s"),
            Arg::new("--write-sub"),
            Arg::new("--all-subs"),
            Arg::new_with_arg("--convert-subs", "lrc"),
            Arg::new_with_arg("--output", "%(title).90s.%(ext)s"),
        ];
        let ytd = YoutubeDL::new("/home/tramhao/Music/mp3/tmp", args, link.as_ref()).unwrap();

        thread::spawn(move || {
            // start download
            let download = ytd.download();

            // check what the result is and print out the path to the download or the error
            match download.result_type() {
                ResultType::SUCCESS => {
                self.refresh();
                // println!("Your download: {}", download.output_dir().to_string_lossy())
                }
                ResultType::IOERROR | ResultType::FAILURE => {
                // println!("Couldn't start download: {}", download.output())
                }
            };
        });
    }

```

**Comment by tramhao** [comment]
the trait `Send` is not implemented for `(dyn tuirealm::Component + 'static)`

**Comment by veeso** [comment]
Hi!

Personally I'd use [mpsc](https://doc.rust-lang.org/std/sync/mpsc/index.html) to implement that.
In the thread you perform the download and using a `Sender` you could send something like

```rust
enum TransferState {
  Progress(Something), // indicates progress
  Completed,
  Err(Error)
}
```

and in the main loop, where you refresh the UI, you listen on the channel with the `Receiver` and whenever a new message is received, you update the UI as you wish.

**Comment by tramhao** [comment]
Thanks so much! This solves my problem!
