### ISSUE TITLE
[BUG] - Textarea cannot scroll

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#13]
## Description

I initialized a textarea, and seems it doesn't respond to keycode up/down etc. It's wierd.
## Steps to reproduce

This is how I setup the textarea
```
            let mut vec_lyric: Vec<TextSpan> = vec![];
            for line in s.lyrics[0].text.split('\n') {
                vec_lyric.push(TextSpan::from(line));
            }
            let props = textarea::TextareaPropsBuilder::from(
                self.view
                    .get_props(super::COMPONENT_TE_TEXTAREA_LYRIC)
                    .unwrap(),
            )
            .with_texts(Some(format!("{} Lyrics:", s.lyrics[0].lang)), vec_lyric)
            .build();
            self.view.update(super::COMPONENT_TE_TEXTAREA_LYRIC, props);

```
## Expected behaviour

It should respond to keyboard directions and pageup/pagedown
## Environment

- OS: Arch linux
- Architecture x86_64
- Rust version: 1.55 nightly
- tui-realm version: 0.4.2

## Additional information

https://github.com/tramhao/termusic for more details.

**Comment by veeso** [comment]
Thanks for reporting the issue.
Yep, it's true, there was a bug.

Fixed in 0..4.3
