### ISSUE TITLE
[Feature Request] - Implement Serializing and Deserialzing for keyevent?

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#28]
## Description

I need to save the key config so that I can change it in config.

### Changes

Implement serializing and deserialing for keyevent.

- ...

## Implementation

Haven't thought of how to do it.

**Comment by veeso** [comment]
Merged into 1.4.0 version.

Please, add the `serialize` feature into your cargo.toml to tui-realm feature, in order to use `Deserialize` and `Serialize` traits.

**Comment by tramhao** [comment]
thanks so much!

**Comment by tramhao** [comment]
I'm getting lost here. Thanks for your implementation of serialize and deserialize. However, I'm facing two problems here:
1. I cannot write it to toml. Probably it's lack of certain feature. Save is always failed due to wrong type.
2. I cannot use any configuration value from config, in component implementation. Is there a better way to do it?

Thanks so much!
