### ISSUE TITLE
[BUG] - Cannot serialize KeyEvent

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#31]
I'm getting lost here. Thanks for your implementation of serialize and deserialize. However, I'm facing two problems here:

I cannot write it to toml. Probably it's lack of certain feature. Save is always failed due to wrong type.
I cannot use any configuration value from config, in component implementation. Is there a better way to do it?
Thanks so much!

**Comment by tramhao** [comment]
should I implement a userevent for each key and register a port to handle them? 
I saw that if I use userevent, I need to modify all components, right? Thanks.

**Comment by veeso** [comment]
Solved in 1.4.1
