### ISSUE TITLE
[QUESTION] - Impl hotkey handler

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#33]
I'm using port to implement hotkey handler as below:
```rust
#[derive(PartialEq, Clone, PartialOrd)]
pub enum UserEvent {
    QuitApp, // ... other events if you need
}
impl Eq for UserEvent {}

impl Poll<UserEvent> for HotkeyHandler {
    fn poll(&mut self) -> ListenerResult<Option<Event<UserEvent>>> {
        // ... do something ...
        Ok(Some(Event::User(UserEvent::QuitApp)))
    }
}
pub struct HotkeyHandler {}

impl HotkeyHandler {
    pub fn new() -> Self {
        Self {}
    }
    // ...
}
```

Is this the correct way? How can I read user input here in HotkeyHandler? Sorry for the problem caused.

**Comment by tramhao** [comment]
Let me state what I want to do here:
I want to save a copy of key config to hotkey handler, and when user press a key, I compare it with config value, if it's the same, I'll send the user event to other part of the app. 
Is it the right way to do it? Thanks.

**Comment by tramhao** [comment]
The following code doesn't work. Do you know why? Thanks so much.
```rust
            Event::Keyboard(key) if key == self.config.key_quit => Some(Msg::QuitPopupShow),

```

**Comment by tramhao** [comment]
Yes I just figured out why it's not working. I didn't register them for global subscriptions.

**Comment by veeso** [comment]
Sorry for the late answer, but I'm on vacation these days.

You could also use a GlobalListener component, using a Phantom (from the stdlib) which takes the configuration as input argument and produces the message, based on the incoming key. In this case, you should subscribe to all events and match those configured by the user.
