### ISSUE TITLE
[BUG] - key and keymodifiers serde format

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#35]
## Description

I'm using a struct as below: 
```rust
#[derive(Clone, Deserialize, Serialize)]
pub struct KeyBind {
    code: Key,
    modifiers: KeyModifiers,
}
```

The information in config.toml is grouped wrongly as below:
```rust

[keys.global_player_seek_backward.modifiers]
type = "KeyModifiers"
bits = 0
[keys.global_lyric_adjust_forward.code]
type = "Char"
args = "F"

[keys.global_lyric_adjust_forward.modifiers]
type = "KeyModifiers"
bits = 1
[keys.global_lyric_adjust_backward.code]
type = "Char"
args = "B"

[keys.global_lyric_adjust_backward.modifiers]
type = "KeyModifiers"
bits = 1
[keys.global_lyric_cycle.code]
type = "Char"
args = "T"

[keys.global_lyric_cycle.modifiers]
type = "KeyModifiers"
bits = 1
[keys.global_color_editor_open.code]
type = "Char"
args = "C"

[keys.global_color_editor_open.modifiers]
type = "KeyModifiers"
bits = 1
```
### Changes

The empty line should happen between too different keys, not within the same key.

**Comment by veeso** [comment]
🤷🏻‍♂️  unfortunately this is done as-is by the TOML crate, so I have no way to fix this. I suggest you anyway to provide a UI on your application to configure keys, in order to prevent the user to edit manually the TOML. In that case, this issue shouldn't be a problem.

**Comment by tramhao** [comment]
yes, probably the best way is to provide an interface to do the job. Thanks!
