### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by andyslucky** [veeso/tui-realm#36]
Hey, I am currently working on a tui application that connects to a database using the sqlx crate. These operations are async and I currently use the tokio crate as an async runtime.  I would love to simplify alot of the components in my project using this crate, however I cannot give up my async operations. Is there a roadmap/ expectation that async will be supported in the future? I suppose the only function that would need to be async is the update fn in the Update trait, but there may be other useful candidates.

**Comment by LukasDoesDev** [comment]
You can put tokio on another thread and use `std::sync::mpsc` to communicate between the TUI thread and the sqlx thread.
