### ISSUE TITLE
Is it posible make apps with large amount of text?

### ISSUE THREAD

**Issue by realtica** [veeso/tui-realm#38]
I need to know if it's possible to make an app like a table with a lot of columns and rows, and filtered typing an input, without flickering or large consume of CPU.

**Comment by realtica** [comment]
Please, I need to know if it's possible..

**Comment by veeso** [comment]
I don't know, if you tried the table component from the stdlib and adjusted the poll interval and the performance is still bad, I suppose it's not. I've never tried to be honest. Can you show me your implementation please?

**Comment by realtica** [comment]
> I don't know, if you tried the table component from the stdlib and adjusted the poll interval and the performance is still bad, I suppose it's not. I've never tried to be honest. Can you show me your implementation please?

Please think as an ideal scenery, because the app is not implemented yet.
Tui-realm(tui-rs) redraws only an area? or redraw all controls?
For example, I have an input text and a table with data, when I type some chars only redraws the area of input, or redraws the input and the table?
Other example, I have an list with scrollbar and and other controls, when I drag the scrollbar, only the list is redraw? or all the controls are redraw?

**Comment by veeso** [comment]
As far as I know, tui-rs redraws only the area which has changed, but to be sure you should ask it directly to the author of the library.
