### ISSUE TITLE
[BUG] - Tricky problem about focus

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm#40]
I found a trick problem about focus as below:
1. I open a popup named tageditor from treeview.
2. In the popup, I do some operation, that will lead to a reload of treeview. And because of the reload, treeview is no longer in focus stack.
3. After I close the tageditor popup, I don't have focus.

Currently I'm focusing treeview manually. But it could get worse. For example, from the popup, there could be error popup mounted. The error message could be showing before or after closing tageditor popup. And now it's very hard to know where to focus.

Is it possible that a remount will not change focus stack?

**Comment by veeso** [comment]
Fixed in 1.7.1
