### ISSUE TITLE
[BUG] - Undefined function in Counter example

### ISSUE THREAD

**Issue by LeonardoDeFaveri** [veeso/tui-realm#43]
## Description

In the counter example, in the implementation of the `view` function for `Counter`, there's this block of code:
```
frame.render_widget(
    Paragraph::new(text)
        .block(get_block(borders, title, focus))
        .style(
            Style::default()
                .fg(foreground)
                .bg(background)
                .add_modifier(modifiers),
        )
        .alignment(alignment),
    area,
);
```

The function `get_block` isn't defined anywhere.

**Comment by veeso** [comment]
Hi,

get_block is defined here https://github.com/veeso/tui-realm/blob/main/examples/components/mod.rs

**Comment by vdawg-git** [comment]
Hey, I cant find the function too :D
