### ISSUE TITLE
How to use complex state values?

### ISSUE THREAD

**Issue by liebkne** [veeso/tui-realm#44]
How can/should I use complex state values (like custom struct?) other than the following ones? Thanks.

```rs
/// State describes a component state
#[derive(Debug, PartialEq, Clone)]
pub enum State {
    One(StateValue),
    Tup2((StateValue, StateValue)),
    Tup3((StateValue, StateValue, StateValue)),
    Tup4((StateValue, StateValue, StateValue, StateValue)),
    Vec(Vec<StateValue>),
    Map(HashMap<String, StateValue>),
    Linked(LinkedList<State>),
    None,
}
```

**Comment by veeso** [comment]
You cannot use custom types in `State`. So basically to pass structures there are 3 ways:

1. You `Msg` instead with custom types
2. Convert your structure in a `State` which uses `StateValue` for example using the `Map` variant
3. Serialize your struct into a string (using json for example)

**Comment by liebkne** [comment]
Thanks for your suggestions. Can you give some more information about method 1?

**Comment by veeso** [comment]
Send an event to your component and just return a `Msg::Something(MyData)` as the return type for that event.

There is a full explanation on how the library works in the documentation: <https://github.com/veeso/tui-realm/blob/main/docs/en/get-started.md>

**Comment by liebkne** [comment]
Thanks!
