### ISSUE TITLE
[QUESTION] - How to make a subscription with an UserEvent which is an enum with fields

### ISSUE THREAD

**Issue by Wade-Lee** [veeso/tui-realm#51]
Hi! I notice there is an example about how to setup a port for polling UserEvent and how to make a subscription with Tick event for a component in the file advanced.md. What I wonder is how to make a subscription with an UserEvent which is an **enum with fields** for a component. For example, I need to sub UserEvent::GotData(Data) for my component as below:
    Sub::new(SubEventClause::User(UserEvent::GotData(Data)), SubClause::Always)
But the complie error is:
    expected value, found struct `Data`

If I give an instance of Data in the Sub function, then there will be no compile error but the subscription has no effect. Could you tell me how to make this kind of subscription?

Many Thanks!

**Comment by veeso** [comment]
The sub clause match for user events depends on your `PartialEq` implementation. You can see the example here https://github.com/veeso/tui-realm/blob/main/examples/user_events/user_events.rs

**Comment by Wade-Lee** [comment]
> The sub clause match for user events depends on your `PartialEq` implementation. You can see the example here https://github.com/veeso/tui-realm/blob/main/examples/user_events/user_events.rs

Aha! That is the exact answer I want. A little tricky, but saved some performance then just use SubEventClause::Any. Thanks a lot!
I can close this question now.
