### ISSUE TITLE
[BUG] - windows: one off error in powershell

### ISSUE THREAD

**Issue by strowk** [veeso/tui-realm#56]
## Description

First row and first column of a terminal are not drawn on when running example "demo" in Powershell.

## Steps to reproduce

In windows 11 run standard terminal application. 
Clone repo and run `cargo run --example demo`

You would see that app renders in wrong bounds.

<img width="860" alt="image" src="https://github.com/veeso/tui-realm/assets/25692644/79ef5afd-e94c-4e1c-86c7-e2210d2b51d8">

## Expected behaviour

Should take terminal completely for render.

## Environment

- OS: Windows
- Architecture: x86_64,
- Rust version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
- tui-realm version: 1.9.0

## Additional information

Might be a bug with crossterm possibly?

If terminal is resized (resize window) - it fixes the issue, app starts rendering correctly.

If running git bash from same terminal, it works the same.

When git bash is run from its own terminal, then usual cargo run leads to totally broken terminal, but running using winpty  ( `winpty cargo run --example demo` ) reproduces the issue differently - first two rows are left, but first column is drawn over correctly.

**Comment by veeso** [comment]
fixed in 1.9.1
