### ISSUE TITLE
[Feature Request] - Async Support

### ISSUE THREAD

**Issue by qcho** [veeso/tui-realm#82]
## Description

Hi,

I'm new to the ratatui ecosystem and loved the value proposition from `tui-realm`. I'm working in a cpu intensive app with several background services and I'm interested in using this app async. I've found a closed issue: 
* #36 

It seems things changed since we now have a ratatui async template to work with:
* https://github.com/ratatui-org/templates/tree/main/simple-async

### Changes

https://github.com/ratatui-org/templates/blob/0c081ee679de1373fce05078cd08861b75e8f47e/simple-async/README.md?plain=1#L1-L184

**Comment by veeso** [comment]
Async makes sense if there is some async io at a certain point. This is not the case. The template has just implemented a wrapper on the event listener, which is something that doesn't provide any advantage. If you want to use async with tui-realm just wrap the entire App in an async worker.
